const form = document.querySelector<HTMLFormElement>("[data-charity-offer-form]");
const cards = Array.from(document.querySelectorAll<HTMLElement>("[data-charity-offer]"));
const resultCount = document.querySelector<HTMLElement>("[data-charity-result-count]");
const emptyState = document.querySelector<HTMLElement>("[data-charity-empty-state]");
const allowed: Record<string, Set<string>> = { category: new Set(["office-collaboration","communications-design","work-management","finance-payroll","crm-fundraising","meetings-events","payments","security","ai-cloud-developer"]), benefit: new Set(["donated-plan","donated-licences","subscription-discount","transaction-rate","usage-credit","advertising-credit","competitive-grant"]), eligibility: new Set(["explicitly-eligible","registered-charity-route","confirm-first"]) };
const control = (name: string) => form?.elements.namedItem(name) as HTMLInputElement | HTMLSelectElement | null;
const includes = (value: string | undefined, selected: string) => !selected || (value ?? "").split(",").includes(selected);
const load = () => { form?.reset(); const params = new URLSearchParams(location.search); for (const [key, value] of params) { const item = control(key); if (!item) continue; if (key === "q") item.value = value.slice(0, 120); else if (allowed[key]?.has(value)) item.value = value; } };
const apply = (mode: "push" | "replace" = "replace") => { if (!form || !resultCount || !emptyState) return; const q = (control("q")?.value ?? "").trim().toLowerCase(); const category = control("category")?.value ?? ""; const benefit = control("benefit")?.value ?? ""; const eligibility = control("eligibility")?.value ?? ""; let count = 0; cards.forEach((card) => { const visible = (!q || (card.dataset.search ?? "").includes(q)) && includes(card.dataset.categories, category) && includes(card.dataset.benefits, benefit) && (!eligibility || card.dataset.eligibility === eligibility); card.hidden = !visible; if (visible) count++; }); resultCount.textContent = `${count} ${count === 1 ? "programme" : "programmes"}`; emptyState.hidden = count !== 0; const params = new URLSearchParams(); if (q) params.set("q", q); if (category) params.set("category", category); if (benefit) params.set("benefit", benefit); if (eligibility) params.set("eligibility", eligibility); history[mode === "push" ? "pushState" : "replaceState"]({}, "", `${location.pathname}${params.size ? `?${params}` : ""}`); };
if (form) { load(); form.addEventListener("submit", (event) => { event.preventDefault(); apply("push"); }); form.addEventListener("input", () => apply()); form.addEventListener("change", () => apply("push")); document.querySelectorAll<HTMLElement>("[data-charity-clear]").forEach((button) => button.addEventListener("click", () => { form.reset(); apply("push"); })); addEventListener("popstate", () => { load(); apply(); }); apply(); }
